{% set version = '1.0.4' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-wallace
  version: {{ version|replace("-", "_") }}

source:
  fn: wallace_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/wallace_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/wallace/wallace_{{ version }}.tar.gz
  sha256: e60041fe1db6d2bf28a55f04e2fe8bdf264ebda8208745b6bbfc91f4c101aca9


  # patches:
   # List any patch files here
   # - fix.patch

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  noarch: generic

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: knitr, rmarkdown, testthat, RSelenium
requirements:
  build:

  host:
    - r-base
    - r-dt >=0.2
    - r-enmeval
    - r-rcolorbrewer
    - r-dismo
    - r-dplyr
    - r-leaflet >=1.0.1
    - r-leaflet.extras
    - r-magrittr
    - r-maptools
    - r-raster
    - r-rgdal
    - r-rgeos
    - r-shiny >=0.14.2
    - r-shinyjs
    - r-shinythemes
    - r-spthin
    - r-spocc >=0.5.4

  run:
    - r-base
    - r-dt >=0.2
    - r-enmeval
    - r-rcolorbrewer
    - r-dismo
    - r-dplyr
    - r-leaflet >=1.0.1
    - r-leaflet.extras
    - r-magrittr
    - r-maptools
    - r-raster
    - r-rgdal
    - r-rgeos
    - r-shiny >=0.14.2
    - r-shinyjs
    - r-shinythemes
    - r-spthin
    - r-spocc >=0.5.4

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('wallace')"           # [not win]
    - "\"%R%\" -e \"library('wallace')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://wallaceEcoMod.github.io
  license: GPL-3
  summary: The 'shiny' application 'wallace' is a modular platform for reproducible modeling
    of species niches and distributions. 'wallace' guides users through a complete analysis,
    from the acquisition of species occurrence and environmental data to visualizing
    model predictions on an interactive map, thus bundling complex workflows into a
    single, streamlined interface.
  license_family: GPL3



# The original CRAN metadata for this package was:

# Package: wallace
# Version: 1.0.4
# Date: 2018-02-12
# Title: A Modular Platform for Reproducible Modeling of Species Niches and Distributions
# Authors@R: c(person("Jamie M.", "Kass", email = "jkass@gradcenter.cuny.edu", role = c("aut", "cre")), person("Bruno", "Vilela", email = "bvilela@wustl.edu", role = "aut"), person("Matthew E.", "Aiello-Lammens", email = "matt.lammens@gmail.com", role = "aut"), person("Robert", "Muscarella", email = "bob.muscarella@gmail.com", role = "aut"), person("Cory", "Merow", email = "corymerow@gmail.com", role = "aut"), person("Robert P.", "Anderson", email = "randerson@ccny.cuny.edu", role = "aut"))
# Author: Jamie M. Kass [aut, cre], Bruno Vilela [aut], Matthew E. Aiello-Lammens [aut], Robert Muscarella [aut], Cory Merow [aut], Robert P. Anderson [aut]
# Maintainer: Jamie M. Kass <jkass@gradcenter.cuny.edu>
# Depends: R (>= 3.2.1), shiny (>= 0.14.2), leaflet (>= 1.0.1)
# Imports: DT (>= 0.2), shinyjs, spocc (>= 0.5.4), RColorBrewer, dplyr, spThin, ENMeval, rgeos, maptools, dismo, raster, shinythemes, magrittr, rgdal, leaflet.extras
# Description: The 'shiny' application 'wallace' is a modular platform for reproducible modeling of species niches and distributions. 'wallace' guides users through a complete analysis, from the acquisition of species occurrence and environmental data to visualizing model predictions on an interactive map, thus bundling complex workflows into a single, streamlined interface.
# License: GPL-3
# URL: https://wallaceEcoMod.github.io
# Encoding: UTF-8
# RoxygenNote: 6.0.1
# Suggests: knitr, rmarkdown, testthat, RSelenium
# NeedsCompilation: no
# Packaged: 2018-02-12 21:29:22 UTC; musasabi
# Repository: CRAN
# Date/Publication: 2018-02-12 21:39:46 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
