{% set version = '0.6.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rbison
  version: {{ version|replace("-", "_") }}

source:
  fn: rbison_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/rbison_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/rbison/rbison_{{ version }}.tar.gz
  sha256: 30348929d2215343586e44139ca95d4e6fdd46cb0a23c95ea338686bca84ab26


  # patches:
   # List any patch files here
   # - fix.patch

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  noarch: generic

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: roxygen2 (>= 6.0.1), knitr, testthat, taxize
requirements:
  build:

  host:
    - r-base
    - r-crul >=0.3.4
    - r-dplyr >=0.5.0
    - r-ggplot2
    - r-jsonlite >=1.1
    - r-mapproj
    - r-plyr
    - r-sp

  run:
    - r-base
    - r-crul >=0.3.4
    - r-dplyr >=0.5.0
    - r-ggplot2
    - r-jsonlite >=1.1
    - r-mapproj
    - r-plyr
    - r-sp

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('rbison')"           # [not win]
    - "\"%R%\" -e \"library('rbison')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/ropensci/rbison
  license: MIT + file LICENSE
  summary: Interface to the 'USGS' 'BISON' (<https://bison.usgs.gov/>) 'API', a 'database' for
    species occurrence data. Data comes from species in the United States from participating
    data providers. You can get data via 'taxonomic' and location based queries. A simple
    function is provided to help visualize data.
  license_family: MIT



# The original CRAN metadata for this package was:

# Package: rbison
# Title: Interface to the 'USGS' 'BISON' 'API'
# Description: Interface to the 'USGS' 'BISON' (<https://bison.usgs.gov/>) 'API', a 'database' for species occurrence data. Data comes from species in the United States from participating data providers. You can get data via 'taxonomic' and location based queries. A simple function is provided to help visualize data.
# Version: 0.6.0
# License: MIT + file LICENSE
# URL: https://github.com/ropensci/rbison
# BugReports: https://github.com/ropensci/rbison/issues
# Authors@R: c(person("Scott", "Chamberlain",  role = c("aut", "cre"), email = "myrmecocystus@gmail.com", comment = "http://orcid.org/0000-0003-1444-9135"))
# LazyData: true
# VignetteBuilder: knitr
# Imports: plyr, crul (>= 0.3.4), ggplot2, mapproj, grid, sp, dplyr (>= 0.5.0), jsonlite (>= 1.1)
# Suggests: roxygen2 (>= 6.0.1), knitr, testthat, taxize
# RoxygenNote: 6.0.1
# X-schema.org-applicationCategory: Data Access
# X-schema.org-keywords: species, occurrences, biodiversity, maps
# X-schema.org-isPartOf: "https://ropensci.org"
# NeedsCompilation: no
# Packaged: 2018-04-11 05:29:05 UTC; sckott
# Author: Scott Chamberlain [aut, cre] (<https://orcid.org/0000-0003-1444-9135>)
# Maintainer: Scott Chamberlain <myrmecocystus@gmail.com>
# Repository: CRAN
# Date/Publication: 2018-04-11 05:48:01 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
