{% set version = '0.2.2' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-enmeval
  version: {{ version|replace("-", "_") }}

source:
  fn: ENMeval_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/ENMeval_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/ENMeval/ENMeval_{{ version }}.tar.gz
  sha256: 2ce14540ce37faa401bad61f5a2144d4547662d857aeff7ba7a8cfde2b9315f1


  # patches:
   # List any patch files here
   # - fix.patch

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  noarch: generic

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: knitr, rmarkdown, spocc, maptools, rgeos
requirements:
  build:

  host:
    - r-base
    - r-dismo
    - r-doparallel
    - r-foreach
    - r-rjava >=0.5_0
    - r-raster

  run:
    - r-base
    - r-dismo
    - r-doparallel
    - r-foreach
    - r-rjava >=0.5_0
    - r-raster

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('ENMeval')"           # [not win]
    - "\"%R%\" -e \"library('ENMeval')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=ENMeval
  license: GPL
  summary: Automatically partitions data into evaluation bins, executes ecological niche models
    across a range of settings, and calculates a variety of evaluation statistics.  Current
    version only implements ENMs with Maxent (Phillips et al. 2006)<doi:10.1016/j.ecolmodel.2005.03.026>.
  license_family: GPL



# The original CRAN metadata for this package was:

# Package: ENMeval
# Type: Package
# Title: Automated Runs and Evaluations of Ecological Niche Models
# Version: 0.2.2
# Date: 2017-1-4
# Author: Robert Muscarella, Peter J. Galante, Mariano Soley-Guardia, Robert A. Boria, Jamie M. Kass, Maria Uriarte and Robert P. Anderson
# Maintainer: Robert Muscarella <bob.muscarella@gmail.com>
# Description: Automatically partitions data into evaluation bins, executes ecological niche models across a range of settings, and calculates a variety of evaluation statistics.  Current version only implements ENMs with Maxent (Phillips et al. 2006)<doi:10.1016/j.ecolmodel.2005.03.026>.
# License: GPL
# Depends: dismo, methods, rJava (>= 0.5-0), parallel, R (>= 2.10)
# Imports: doParallel, foreach, utils, graphics, stats, grDevices, raster
# Suggests: knitr, rmarkdown, spocc, maptools, rgeos
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2017-01-09 22:29:39 UTC; Bob
# Repository: CRAN
# Date/Publication: 2017-01-10 10:17:38

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
