{% set version = '0.4.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-wicket
  version: {{ version|replace("-", "_") }}

source:
  fn: wicket_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/wicket_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/wicket/wicket_{{ version }}.tar.gz
  sha256: ce76a4c8f79e7dfb9d8aadfa59b7f5cdb0de3dd9623b1426fd5caf6464fd3fd2


  # patches:
   # List any patch files here
   # - fix.patch

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat, knitr, rmarkdown
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make

  host:
    - r-base
    - r-bh
    - r-rcpp

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-bh
    - r-rcpp

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('wicket')"           # [not win]
    - "\"%R%\" -e \"library('wicket')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/ropensci/wicket
  license: MIT + file LICENSE
  summary: Utilities to generate bounding boxes from 'WKT' (Well-Known Text) objects and R data
    types, validate 'WKT' objects and convert object types from the 'sp' package into
    'WKT' representations.
  license_family: MIT



# The original CRAN metadata for this package was:

# Package: wicket
# Type: Package
# Title: Utilities to Handle WKT Spatial Data
# Version: 0.4.0
# Date: 2017-11-18
# Author: Oliver Keyes [aut, cre]
# Maintainer: Oliver Keyes <ironholds@gmail.com>
# Description: Utilities to generate bounding boxes from 'WKT' (Well-Known Text) objects and R data types, validate 'WKT' objects and convert object types from the 'sp' package into 'WKT' representations.
# License: MIT + file LICENSE
# LazyData: TRUE
# LinkingTo: Rcpp, BH
# Imports: Rcpp
# RoxygenNote: 6.0.1
# Suggests: testthat, knitr, rmarkdown
# VignetteBuilder: knitr
# URL: https://github.com/ropensci/wicket
# BugReports: https://github.com/ropensci/wicket/issues
# NeedsCompilation: yes
# Packaged: 2017-11-18 23:43:08 UTC; ironholds
# Repository: CRAN
# Date/Publication: 2017-11-19 17:20:10 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
