# This file lists acceptable images to allow runing.
#
# This allows you, the admin, to create multiple flavours
# for your users to run. E.g. maybe you need a geosciences flavour,
# you can create the image based on our default image and add the
# appropriate `apt-get/pip install` statements.
---
-
    image: shiny-gie-gis-region:latest
    mako: mako.mako
    description: |
      Map observations on Regions
-
    image: shiny-gie-gis-plot:latest
    mako: pas.mako
    description : |
      Map observations and plot data
-
    image: shiny-wallace:dev
    description : |
      Reproducible modeling of species niches and distributions
-
    image: shiny-ww-eqs:latest
    description : |
      earthQuake
