{% set version = '0.3.5' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ridigbio
  version: {{ version|replace("-", "_") }}

source:
  fn: ridigbio_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/ridigbio_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/ridigbio/ridigbio_{{ version }}.tar.gz
  sha256: e5cfb2e4dd8ddd1452a5afcf24fcc260889179d0f52eff4f41835adf99b64614


  # patches:
   # List any patch files here
   # - fix.patch

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  noarch: generic

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat
requirements:
  build:

  host:
    - r-base
    - r-httr
    - r-jsonlite
    - r-plyr

  run:
    - r-base
    - r-httr
    - r-jsonlite
    - r-plyr

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('ridigbio')"           # [not win]
    - "\"%R%\" -e \"library('ridigbio')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/iDigBio/ridigbio
  license: MIT + file LICENSE
  summary: An interface to iDigBio's search API that allows downloading specimen records. Searches
    are returned as a data.frame. Other functions such as the metadata end points return
    lists of information. iDigBio is a US project focused on digitizing and serving
    museum specimen collections on the web. See <https://www.idigbio.org> for information
    on iDigBio.
  license_family: MIT



# The original CRAN metadata for this package was:

# Package: ridigbio
# Title: Interface to the iDigBio Data API
# Version: 0.3.5
# Date: 2017-02-16
# Authors@R: c(person("Francois", "Michonneau", role=c("aut", "cph"), email="francois.michonneau@gmail.com"), person("Matthew", "Collins", role=c("aut", "cre"), email="mcollins@acis.ufl.edu"), person("Scott", "Chamberlain", role="ctb", email="myrmecocystus@gmail.com"), person("Kevin", "Love", role="ctb", email="klove@flmnh.ufl.edu"), person("Hem Nalini", "Morzaria-Luna", role="ctb", email="hemnalin.morzarialuna@noaa.gov"))
# Description: An interface to iDigBio's search API that allows downloading specimen records. Searches are returned as a data.frame. Other functions such as the metadata end points return lists of information. iDigBio is a US project focused on digitizing and serving museum specimen collections on the web. See <https://www.idigbio.org> for information on iDigBio.
# URL: https://github.com/iDigBio/ridigbio
# BugReports: https://github.com/iDigBio/ridigbio/issues
# Depends: R (>= 3.0.1)
# Imports: stats, plyr, httr, jsonlite
# License: MIT + file LICENSE
# LazyData: true
# Suggests: testthat
# Repository: CRAN
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2017-02-16 15:17:45 UTC; mcollins
# Author: Francois Michonneau [aut, cph], Matthew Collins [aut, cre], Scott Chamberlain [ctb], Kevin Love [ctb], Hem Nalini Morzaria-Luna [ctb]
# Maintainer: Matthew Collins <mcollins@acis.ufl.edu>
# Date/Publication: 2017-02-16 17:57:11

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
