{% set version = '0.2.2' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-oai
  version: {{ version|replace("-", "_") }}

source:
  fn: oai_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/oai_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/oai/oai_{{ version }}.tar.gz
  sha256: a1eef45c7faf1b12613b1e782847cc6f8994ffe917f1b694d325de9b79123c60


  # patches:
   # List any patch files here
   # - fix.patch

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: roxygen2 (>= 5.0.1), DBI, knitr, RSQLite, testthat, covr
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make

  host:
    - r-base
    - r-httr >=1.2.0
    - r-plyr >=1.8.4
    - r-stringr >=1.1.0
    - r-tibble >=1.2
    - r-xml2 >=1.0.0

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-httr >=1.2.0
    - r-plyr >=1.8.4
    - r-stringr >=1.1.0
    - r-tibble >=1.2
    - r-xml2 >=1.0.0

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('oai')"           # [not win]
    - "\"%R%\" -e \"library('oai')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/ropensci/oai
  license: MIT + file LICENSE
  summary: 'A general purpose client to work with any ''OAI-PMH'' (Open Archives Initiative Protocol
    for ''Metadata'' Harvesting) service. The ''OAI-PMH'' protocol is described at <http://www.openarchives.org/OAI/openarchivesprotocol.html>.
    Functions are provided to work with the ''OAI-PMH'' verbs: ''GetRecord'', ''Identify'',
    ''ListIdentifiers'', ''ListMetadataFormats'', ''ListRecords'', and ''ListSets''.'

  license_family: MIT



# The original CRAN metadata for this package was:

# Package: oai
# Type: Package
# Title: General Purpose 'Oai-PMH' Services Client
# Description: A general purpose client to work with any 'OAI-PMH' (Open Archives Initiative Protocol for 'Metadata' Harvesting) service. The 'OAI-PMH' protocol is described at <http://www.openarchives.org/OAI/openarchivesprotocol.html>. Functions are provided to work with the 'OAI-PMH' verbs: 'GetRecord', 'Identify', 'ListIdentifiers', 'ListMetadataFormats', 'ListRecords', and 'ListSets'.
# Version: 0.2.2
# License: MIT + file LICENSE
# Authors@R: c( person("Scott", "Chamberlain", role = c("aut", "cre"), email = "myrmecocystus@gmail.com"), person("Michal", "Bojanowski", role = "aut") )
# URL: https://github.com/ropensci/oai
# BugReports: https://github.com/ropensci/oai/issues
# VignetteBuilder: knitr
# LazyData: true
# Imports: xml2 (>= 1.0.0), httr (>= 1.2.0), plyr (>= 1.8.4), stringr (>= 1.1.0), tibble (>= 1.2)
# Suggests: roxygen2 (>= 5.0.1), DBI, knitr, RSQLite, testthat, covr
# RoxygenNote: 5.0.1
# NeedsCompilation: yes
# Packaged: 2016-11-23 22:59:08 UTC; sacmac
# Author: Scott Chamberlain [aut, cre], Michal Bojanowski [aut]
# Maintainer: Scott Chamberlain <myrmecocystus@gmail.com>
# Repository: CRAN
# Date/Publication: 2016-11-24 00:06:39

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
