{% set version = '0.1.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-spthin
  version: {{ version|replace("-", "_") }}

source:
  fn: spThin_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/spThin_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/spThin/spThin_{{ version }}.tar.gz
  sha256: f7cae792a1a04abaa44478c3f54eae5e2b87ebb48ce4c57df0f4701531980b1b


  # patches:
   # List any patch files here
   # - fix.patch

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  noarch: generic

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:

  host:
    - r-base
    - r-fields
    - r-knitr
    - r-spam

  run:
    - r-base
    - r-fields
    - r-knitr
    - r-spam

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('spThin')"           # [not win]
    - "\"%R%\" -e \"library('spThin')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=spThin
  license: GPL-3
  summary: spThin is a set of functions that can be used to spatially thin species occurrence
    data. The resulting thinned data can be used in ecological modeling, such as ecological
    niche modeling.
  license_family: GPL3



# The original CRAN metadata for this package was:

# Package: spThin
# Type: Package
# Title: Functions for Spatial Thinning of Species Occurrence Records for Use in Ecological Models
# Version: 0.1.0
# Date: 2014-11-16
# Author: Matthew E. Aiello-Lammens, Robert A. Boria, Aleksandar Radosavljevic, Bruno Vilela, and Robert P. Anderson
# Maintainer: Matthew E. Aiello-Lammens <matt.lammens@gmail.com>
# Description: spThin is a set of functions that can be used to spatially thin species occurrence data. The resulting thinned data can be used in ecological modeling, such as ecological niche modeling.
# Depends: spam, grid, fields, knitr
# LazyData: TRUE
# License: GPL-3
# VignetteBuilder: knitr
# Packaged: 2014-11-17 02:17:13 UTC; mlammens
# NeedsCompilation: no
# Repository: CRAN
# Date/Publication: 2014-11-17 08:57:55

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
