{% set version = '0.1.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-geoaxe
  version: {{ version|replace("-", "_") }}

source:
  fn: geoaxe_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/geoaxe_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/geoaxe/geoaxe_{{ version }}.tar.gz
  sha256: 7ba4e5285670e67e307224222fcee5f7d6b67b6c1a5f7b8f34e64222d63c7e10


  # patches:
   # List any patch files here
   # - fix.patch

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  noarch: generic

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat, knitr
requirements:
  build:

  host:
    - r-base
    - r-jsonlite
    - r-rgeos
    - r-sp

  run:
    - r-base
    - r-jsonlite
    - r-rgeos
    - r-sp

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('geoaxe')"           # [not win]
    - "\"%R%\" -e \"library('geoaxe')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/ropenscilabs/geoaxe
  license: MIT + file LICENSE
  summary: Split 'geospatial' objects into pieces. Includes support for some spatial object inputs,
    'Well-Known Text', and 'GeoJSON'.
  license_family: MIT



# The original CRAN metadata for this package was:

# Package: geoaxe
# Title: Split 'Geospatial' Objects into Pieces
# Description: Split 'geospatial' objects into pieces. Includes support for some spatial object inputs, 'Well-Known Text', and 'GeoJSON'.
# Version: 0.1.0
# License: MIT + file LICENSE
# Authors@R: person("Scott", "Chamberlain", role = c("aut", "cre"), email = "myrmecocystus@gmail.com")
# URL: https://github.com/ropenscilabs/geoaxe
# BugReports: https://github.com/ropenscilabs/geoaxe/issues
# VignetteBuilder: knitr
# Imports: methods, sp, rgeos, jsonlite
# Suggests: testthat, knitr
# RoxygenNote: 5.0.1
# NeedsCompilation: no
# Packaged: 2016-02-19 00:25:56 UTC; sacmac
# Author: Scott Chamberlain [aut, cre]
# Maintainer: Scott Chamberlain <myrmecocystus@gmail.com>
# Repository: CRAN
# Date/Publication: 2016-02-19 08:49:59

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
